#!/usr/bin/perl -w -I./perllib -I../../perllib 
#
# server:
# RABX server for NeWs.
#
# Copyright (c) 2006 UK Citizens Online Democracy. All rights reserved.
# Email: louise.crow@gmail.com; WWW: http://www.mysociety.org/
#

my $rcsid = ''; $rcsid .= '$Id: server,v 1.3 2006-04-16 18:40:14 louise Exp $';

use strict;
require 5.8.0;


# Do this first of all, because NeWs.pm needs to see the config file.
BEGIN {
    use mySociety::Config;
    mySociety::Config::set_file('../conf/general');
}

use FCGI;
use RABX;

use NeWs;

my $req = FCGI::Request();

while ($req->Accept() >= 0) {
    RABX::Server::CGI::dispatch(
            'NeWs.get_newspaper' => sub {
                return NeWs::get_newspaper($_[0]);
            }, 
            'NeWs.get_newspapers' => sub {
                return NeWs::get_newspapers();
            }, 
            'NeWs.publish_update' => sub {
                return NeWs::publish_update($_[0],$_[1],$_[2]);
            },
            'NeWs.get_history' => sub {
                return NeWs::get_history($_[0]);
            }

        );
}
