#!/usr/bin/perl -w -I../../perllib
#
# server:
# RABX server for DaDem.
#
# To run it you need these lines in an Apache config:
#     Options +ExecCGI
#     SetHandler fastcgi-script
#
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#

my $rcsid = ''; $rcsid .= '$Id: server,v 1.7 2005-01-31 19:58:57 chris Exp $';

use strict;
require 5.8.0;

# Do this first of all, because DaDem.pm needs to see the config file.
BEGIN {
    use mySociety::Config;
    mySociety::Config::set_file('../conf/general');
}

use FCGI;
use RABX;

use mySociety::DaDem;   # client interface
use mySociety::VotingArea;
use mySociety::WatchUpdate;

use DaDem;              # implementation

my $W = new mySociety::WatchUpdate();

my $req = FCGI::Request();

while ($req->Accept() >= 0) {
    RABX::Server::CGI::dispatch(
            'DaDem.get_representatives' => sub {
                return DaDem::get_representatives($_[0]);
            },
            'DaDem.search_representatives' => sub {
                return DaDem::search_representatives($_[0]);
            },
            'DaDem.get_representative_info' => sub {
                return DaDem::get_representative_info($_[0]);
            },
            'DaDem.get_representatives_info' => sub {
                return DaDem::get_representatives_info($_[0]);
            },
            'DaDem.get_representative_history' => sub {
                return DaDem::get_representative_history($_[0]);
            },
             'DaDem.admin_get_stats' => sub {
                return DaDem::admin_get_stats();
            },
            'DaDem.admin_edit_representative' => sub {
                return DaDem::admin_edit_representative($_[0], $_[1], $_[2], $_[3]);
            }
         );
    $W->exit_if_changed();
}

