#!/usr/bin/perl -w -I../../perllib
#
# server:
# RABX server for MaPit.
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#

my $rcsid = ''; $rcsid .= '$Id: server,v 1.6 2005-01-19 11:53:20 chris Exp $';

use strict;
require 5.8.0;

use FCGI;
use mySociety::MaPit;   # client interface
use mySociety::VotingArea;
use MaPit;
use RABX;

use mySociety::Config;
mySociety::Config::set_file('../conf/general');

use mySociety::WatchUpdate;
my $W = new mySociety::WatchUpdate();

my $req = FCGI::Request();

while ($req->Accept() >= 0) {
    RABX::Server::CGI::dispatch(
            'MaPit.get_voting_areas' => sub {
                return MaPit::get_voting_areas($_[0]);
            },
            'MaPit.get_example_postcode' => sub {
                return MaPit::get_example_postcode($_[0]);
            },
             'MaPit.get_voting_area_info' => sub {
                return MaPit::get_voting_area_info($_[0]);
            },
            'MaPit.get_voting_areas_info' => sub {
                return MaPit::get_voting_areas_info($_[0]);
            },
            'MaPit.get_voting_area_children' => sub {
                return MaPit::get_voting_area_children($_[0]);
            },
            'MaPit.get_location' => sub {
                return MaPit::get_location($_[0]);
            },
            'MaPit.admin_get_stats' => sub {
                return MaPit::admin_get_stats();
            }
        );
    $W->exit_if_changed();
}




