#!/usr/bin/perl -w -I../perllib -I ../../perllib
#
# 2009-12-update-ni-snac:
# SI 2008/1486 remade all the Northern Ireland Parliamentary Constituencies.
# First, let's update our SNAC file to point the right wards at the right
# constituencies. After writing this, I've found
# http://www.eoni.org.uk/wards_by_district__showing_constituency_.pdf
# which is a good check if nothing else!
#
# Copyright (c) 2009 UK Citizens Online Democracy. All rights reserved.
# Email: matthew@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: 2009-12-update-ni-snac,v 1.1 2009-12-23 23:50:48 matthew Exp $

use strict;
use IO::File;
use Text::CSV_XS;
use Common;

# The wards that actually make up the constituencies.
my %construction = (

    'Belfast East' => {
        'Belfast' => [ 'Ballyhackamore', 'Ballymacarrett', 'Belmont', 'Bloomfield', 'Cherryvalley', 'Island', 'Knock', 'Orangefield', 'Stormont', 'Sydenham', 'The Mount' ],
        'Castlereagh' => [ 'Ballyhanwood', 'Carrowreagh', 'Cregagh', 'Downshire', 'Dundonald', 'Enler', 'Gilnahirk', "Graham's Bridge", 'Lisnasharragh', 'Lower Braniel', 'Tullycarnet', 'Upper Braniel' ]
    },
    'Belfast North' => {
    	'Belfast' => [ 'Ardoyne', 'Ballysillan', 'Bellevue', 'Castleview', 'Cavehill', 'Chichester Park', 'Cliftonville', 'Crumlin', 'Duncairn', 'Fortwilliam', 'Legoniel', 'New Lodge', 'Water Works', 'Woodvale' ],
    	'Newtownabbey' => [ 'Abbey', 'Ballyhenry', 'Cloughfern', 'Collinbridge', 'Coole', 'Dunanney', 'Glebe', 'Glengormley', 'Hightown', 'Valley', 'Whitehouse' ]
    },
    'Belfast South' => {
    	'Belfast' => [ 'Ballynafeigh', 'Blackstaff', 'Botanic', 'Finaghy', 'Malone', 'Musgrave', 'Ravenhill', 'Rosetta', 'Shaftesbury', 'Stranmillis', 'Upper Malone', 'Windsor', 'Woodstock' ],
    	'Castlereagh' => [ 'Beechill', 'Cairnshill', 'Carryduff East', 'Carryduff West', 'Galwally', 'Hillfoot', 'Knockbracken', 'Minnowburn', 'Newtownbreda', 'Wynchurch' ]
    },
    'Belfast West' => {
    	'Belfast' => [ 'Andersonstown', 'Beechmount', 'Clonard', 'Falls', 'Falls Park', 'Glencairn', 'Glencolin', 'Glen Road', 'Highfield', 'Ladybrook', 'Shankill', 'Upper Springfield', 'Whiterock' ],
    	'Lisburn' => [ 'Collin Glen', 'Dunmurry', 'Kilwee', 'Poleglass', 'Twinbrook' ],
    	#in Lisburn local government district', 'that part of Derryaghy ward lying to the north of the Derryaghy and Lagmore townland boundary' ]
    },
    'East Antrim' => {
    	'Carrickfergus' => [],
        'Larne' => [],
    	'Moyle' => [ 'Glenaan', 'Glenariff', 'Glendun' ],
    	'Newtownabbey' => [ 'Jordanstown', 'Monkstown', 'Rostulla' ]
    },
    'East Londonderry' => {
    	'Coleraine' => [],
    	'Derry City' => [ 'Banagher', 'Claudy' ],
    	'Limavady' => [],
    },
    'Fermanagh & South Tyrone' => {
    	'Dungannon and South Tyrone' => [ 'Augher', 'Aughnacloy', 'Ballygawley', 'Ballysaggart', 'Benburb', 'Caledon', 'Castlecaulfield', 'Clogher', 'Coolhill', 'Drumglass', 'Fivemiletown', 'Killyman', 'Killymeal', 'Moy', 'Moygashel', 'Mullaghmore' ],
        'Fermanagh' => [],
    },
    'Foyle' => {
        'Derry City' => [ 'Altnagelvin', 'Ballynashallog', 'Beechwood', 'Brandywell', 'Carn Hill', 'Caw', 'Clondermot', 'Creggan Central', 'Creggan South', 'Crevagh', 'Culmore', 'Ebrington', 'Eglinton', 'Enagh', 'Foyle Springs', 'Holly Mount', 'Kilfennan', 'Lisnagelvin', 'New Buildings', 'Pennyburn', 'Rosemount', 'Shantallow East', 'Shantallow West', 'Springtown', 'Strand', 'The Diamond', 'Victoria', 'Westland' ]
    },
    'Lagan Valley' => {
    	'Banbridge' => [ 'Dromore North', 'Dromore South', 'Gransha', 'Quilly' ],
    	'Lisburn' => [ 'Ballinderry', 'Ballymacash', 'Ballymacbrennan', 'Ballymacoss', 'Blaris', 'Dromara', 'Drumbo', 'Harmony Hill', 'Hilden', 'Hillhall', 'Hillsborough', 'Knockmore', 'Lagan Valley', 'Lambeg', 'Lisnagarvy', 'Maghaberry', 'Magheralave', 'Maze', 'Moira', 'Old Warren', 'Seymour Hill', 'Tonagh', 'Wallace Park' ],
    	#in Lisburn local government district', 'that part of Derryaghy ward lying to the south and east of the Derryaghy and Lagmore townland boundary' ]
    },
    'Mid Ulster' => {
    	'Cookstown' => [],
    	'Dungannon and South Tyrone' => [ 'Altmore', 'Coalisland North', 'Coalisland South', 'Coalisland West and Newmills', 'Donaghmore', 'Washing Bay' ],
    	'Magherafelt' => [],
    },
    'Newry & Armagh' => {
    	'Armagh' => [],
    	'Newry and Mourne' => [ 'Ballybot', 'Bessbrook', 'Camlough', 'Creggan', 'Crossmaglen', 'Daisy Hill', 'Derrymore', 'Drumalane', 'Drumgullion', 'Fathom', 'Forkhill', 'Newtownhamilton', "St. Mary's", "St. Patrick's", 'Silver Bridge', 'Tullyhappy', 'Windsor Hill' ],
    },
    'North Antrim' => {
    	'Ballymena' => [],
        'Ballymoney' => [],
    	'Moyle' => [ 'Armoy', 'Ballylough', 'Bushmills', 'Bonamargy and Rathlin', 'Carnmoon', 'Dalriada', 'Dunseverick', 'Glenshesk', 'Glentaisie', 'Kinbane', 'Knocklayd', 'Moss-Side and Moyarget' ]
    },
    'North Down' => {
    	'Ards' => [ 'Donaghadee North', 'Donaghadee South', 'Millisle' ],
    	'North Down' => [],
    },
    'South Antrim' => {
    	'Antrim' => [],
    	'Lisburn' => [ 'Glenavy' ],
    	'Newtownabbey' => [ 'Ballyclare North', 'Ballyclare South', 'Ballyduff', 'Ballynure', 'Ballyrobert', 'Burnthill', 'Carnmoney', 'Doagh', 'Hawthorne', 'Mallusk', 'Mossley' ]
    },
    'South Down' => {
    	'Banbridge' => [ 'Ballyward', 'Bannside', 'Katesbridge', 'Rathfriland' ],
    	'Down' => [ 'Ardglass', 'Audleys Acre', 'Ballymote', 'Castlewellan', 'Cathedral', 'Crossgar', 'Donard', 'Drumaness', 'Dundrum', 'Dunmore', 'Killough', 'Murlough', 'Quoile', 'Seaforde', 'Shimna', 'Strangford', 'Tollymore' ],
    	'Newry and Mourne' => [ 'Annalong', 'Binnian', 'Burren and Kilbroney', 'Clonallan', 'Derryleckagh', 'Donaghmore', 'Kilkeel Central', 'Kilkeel South', 'Lisnacree', 'Mayobridge', 'Rostrevor', 'Seaview', 'Spelga' ]
    },
    'Strangford' => {
    	'Ards' => [ 'Ballygowan', 'Ballyrainey', 'Ballywalter', "Bradshaw's Brae", 'Carrowdore', 'Central', 'Comber East', 'Comber North', 'Comber West', 'Glen', 'Gregstown', 'Killinchy', 'Kircubbin', 'Lisbane', 'Loughries', 'Movilla', 'Portaferry', 'Portavogie', 'Scrabo', 'Whitespots' ],
    	'Castlereagh' => [ 'Moneyreagh' ],
    	'Down' => [ 'Ballymaglave', 'Ballynahinch East', 'Derryboy', 'Killyleagh', 'Kilmore', 'Saintfield' ]
    },
    'Upper Bann' => {
    	'Banbridge' => [ 'Ballydown', 'Banbridge West', 'Edenderry', 'Fort', 'Gilford', 'Lawrencetown', 'Loughbrickland', 'Seapatrick', 'The Cut' ],
    	'Craigavon' => [],
    },
    'West Tyrone' => {
    	'Omagh' => [],
    	'Strabane' => [],
    }

);

# Quicker than doing it any other way
my %ons_code_to_name = (
    701 => 'Belfast East',
    702 => 'Belfast North',
    703 => 'Belfast South',
    704 => 'Belfast West',
    705 => 'East Antrim',
    706 => 'East Londonderry',
    707 => 'Fermanagh & South Tyrone',
    708 => 'Foyle',
    709 => 'Lagan Valley',
    710 => 'Mid Ulster',
    711 => 'Newry & Armagh',
    712 => 'North Antrim',
    713 => 'North Down',
    714 => 'South Antrim',
    715 => 'South Down',
    716 => 'Strangford',
    717 => 'Upper Bann',
    718 => 'West Tyrone',
);
my %ons_name_to_code = map { $ons_code_to_name{$_} => $_ } keys %ons_code_to_name;

die "argument is ONS codes CSV file" unless (@ARGV == 1);
my ($onscodesfile) = @ARGV;

foreach (read_csv_file($onscodesfile, 1)) {
    # Fields are: ONS constituency code, name; ONS ward code, name; ONS LA/UA code, name
    my ($ccode, $cname, $wcode, $wname, $acode, $aname) = @$_;
    # load Northern Ireland only
    next if ($wcode !~ m/^95/);

    die "undefined constituency code in '$_'" if (!defined($ccode));
    die "undefined ward code in '$_'" if (!defined($wcode));
    die "undefined LA/UA code in '$_'" if (!defined($acode));
    
    foreach my $constituency (keys %construction) {
        foreach my $council (keys %{$construction{$constituency}}) {
            my $whole_council = 1;
            foreach my $ward (@{$construction{$constituency}{$council}}) {
                $whole_council = 0;
                if ($ward eq $wname && $council eq $aname) {
                    print "\"$ons_name_to_code{$constituency}\",\"$constituency\",\"$wcode\",\"$wname\",\"$acode\",\"$aname\"\n";
                }
            }
            if ($whole_council) {
                if ($council eq $aname) {
                    print "\"$ons_name_to_code{$constituency}\",\"$constituency\",\"$wcode\",\"$wname\",\"$acode\",\"$aname\"\n";
                }
            }
        }
    }
}

