#!/usr/bin/perl -w -I../../perllib
#
# test.pl
#
# Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
#

use strict;
$| = 1; # flush STDOUT afer each write

use LWP::Simple;
use Data::Dumper;
use URI;

use mySociety::CouncilMatch;
use mySociety::StringUtils qw(trim merge_spaces);
use HTML::TokeParser;
use Common;

my $m_dbh = connect_to_mapit_database();
my $d_dbh = connect_to_dadem_database();

my $samplecouncils = [

### DONE ###
# CWCWCW
# Surname first
#{id=>2504, url=>"http://www.westminster.gov.uk/councilgovernmentanddemocracy/councils/contactsconsultationandfeedback/councillors/"},

### TRIED ###
# Need subpages -- too hard
# WCWCCC
#{id=>2305, url=>"http://www.rother.gov.uk/index.cfm?articleid=187"},

#
# WCWCCC
#{id=>2287, url=>"http://www.teignbridge.gov.uk/councillors/index.htm"},

# Problems: 
#  - Misspelt ward on council website (correct by changing it for one council!)
#  - Two M Lovatts
# WCWCCC 
# Initials
#{id=>2432, url=>"http://www.staffsmoorlands.gov.uk/whoswho/councillors/councillorsbyward/councillorsbywardlist.htm"},

# Problems, wards are very mangled
# CWCWCW
# Initials
#{id=>2246, url=>"http://www.worcestershire.gov.uk/home/cs-mas-dsu/cs-mas-councillors/cs-mas-your-councillors.htm"}

### VIRGIN ###

# UMS
#{id=>2507, url=>"http://www.upmystreet.com/inf/rep/det/lgc_councillors.php3?l1=n5+1py"}

# CWCWCW
# Recursive map
{id=>2494, url=>"http://www.bexley.gov.uk/about/ward_and_map.html"},

# WCWCCC 
# Middle initials
#{id=>2626, url=>"http://www.broadland.gov.uk/broadland/members.nsf/CouncillorsByWard?openform&Start=1&Count=1000&ExpandView"},

# Problems:
# - :e
# CWCWCW
# Surname first
#{id=>2243, url=>"http://www.warwickshire.gov.uk/corporate%5Ccommitte.nsf/WCalphaWCC?OpenView&expandview&Count=150"},

# CWCWCW 
# Capital surnames
#{id=>2430, url=>"http://www.southsomerset.gov.uk/portal/page?_pageid=69,84872&_dad=cms&_schema=CMS&3410_COUNCILLORS_89102133.l_model=District%20Councillor"},

];

foreach my $spec (@$samplecouncils) {
    check_councillors($spec);
}

$m_dbh->disconnect();
$d_dbh->disconnect();

