#!/usr/bin/perl -w -I../../perllib

#
# create_new_generation:
# Create new generation in MaPit, if there isn't one already.
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#

my $rcsid = ''; $rcsid .= '$Id: create_new_generation,v 1.5 2009-12-22 21:17:38 matthew Exp $';

use strict;

use DBI;
use DBD::Pg;

use Common;

my $dbh = Common::connect_to_mapit_database();
printf "%d\n", new_generation($dbh);
$dbh->commit();
$dbh->disconnect();
