#!/usr/bin/perl -w -I../../perllib

#
# make_new_generation_active:
# Make new generation active in MaPit.
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#

my $rcsid = ''; $rcsid .= '$Id: make_new_generation_active,v 1.3 2009-12-22 21:17:38 matthew Exp $';

use strict;

use DBI;
use DBD::Pg;

use Common;

my $dbh = Common::connect_to_mapit_database();
make_new_generation_active($dbh);
$dbh->commit();
$dbh->disconnect();
