#!/usr/bin/perl -w -I../../perllib
#
# server:
# RABX server for Generic Queue.
#
# To run it you need these lines in an Apache config:
#     Options +ExecCGI
#     SetHandler fastcgi-script
#
#
# Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
#

my $rcsid = ''; $rcsid .= '$Id: genqueue,v 1.1 2005-02-23 08:47:26 francis Exp $';

use strict;
require 5.8.0;

BEGIN {
    use mySociety::Config;
    mySociety::Config::set_file('../conf/general');
}

use FCGI;
use RABX;

use Queue;              # implementation

my $W = new mySociety::WatchUpdate();

my $req = FCGI::Request();

while ($req->Accept() >= 0) {
    RABX::Server::CGI::dispatch(
            'DaDem.get_representatives' => sub {
                return DaDem::get_representatives($_[0]);
            },
         );
    $W->exit_if_changed();
}

