#!/bin/sh
#
# tileserver.cgi:
# Run the tileserver program
#
# Copyright (c) 2006 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: tileserver,v 1.1 2006-09-22 17:08:42 francis Exp $
#
/data/vhost/tilma.mysociety.org/mysociety/services/TilMa/tileserver/tileserver /data/vhost/tilma.mysociety.org/tiledata

