#!/bin/sh
#
# tileserver.cgi:
# Run the tileserver program
#
# Copyright (c) 2006 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: tileserver,v 1.2 2007-02-06 00:26:06 chris Exp $
#
exec /data/vhost/tilma.mysociety.org/mysociety/services/TilMa/tileserver/tileserver /data/vhost/tilma.mysociety.org/tiledata

